source_dataset:
  name: mini

target_dataset:
  type: json_dataset
  name: cub
  args:
    data_file: filelists/cub/novel.json
    transform_list: 
      - Scale
      - CenterCrop
      - ToTensor
      - Normalize
    image_size: 80

test_ep:
  batch_num: 600
  n: 5
  k: 5
  q: 15

model:
  name: paper_model
  args:
    k: 9
    encoder:
      name: wrn
      args: 
        num_classes: 200

max_epoch: 1