test_dataset:
  name: mini
  args:
    tail_path: mini-imagenet/test
    transform_list: 
      - Resize
      - ToTensor
      - Normalize
    image_size: 80

test_ep:
  batch_num: 800
  n: 5
  k: 5
  q: 15

model:
  name: adapt_query
  args:
    encoder:
      name: resnet12
      args: {}

max_epoch: 10