train_dataset:
  type: simple_dataset
  name: tiered
  args:
    tail_path: tiered_imagenet/train
    transform_list: 
      - Resize
      - ToTensor
      - Normalize
    image_size: 84
    
val_dataset:
  type: simple_dataset
  name: tiered
  args:
    tail_path: tiered_imagenet/val
    transform_list: 
      - Resize
      - ToTensor
      - Normalize
    image_size: 84

train_ep:
  batch_num: 10
  n: 5
  k: 1
  q: 15
  
val_ep:
  batch_num: 200
  n: 5
  k: 1
  q: 15

model:
  name: paper_model
  args:
    k: 9
    encoder:
      name: convnet4
      args: {}
      
optimizer:
  name: SGD
  args:
    lr: 0.001
    weight_decay: 5.e-4

max_epoch: 30