train_dataset:
  type: simple_dataset
  name: mini
  args:
    tail_path: mini-imagenet/train
    transform_list: 
      - Resize
      - ToTensor
      - Normalize
    image_size: 84
    
val_dataset:
  type: simple_dataset
  name: mini
  args:
    tail_path: mini-imagenet/val
    transform_list: 
      - Resize
      - ToTensor
      - Normalize
    image_size: 84

train_ep:
  batch_num: 200
  n: 5
  k: 5
  q: 15
  
val_ep:
  batch_num: 200
  n: 5
  k: 5
  q: 15

model:
  name: metric_model
  args:
    k: 9
    metric: manhattan_distance
    encoder:
      name: convnet4
      args: {}
      
optimizer:
  name: SGD
  args:
    lr: 0.001
    weight_decay: 5.e-4

max_epoch: 30