train_dataset:
  type: json_dataset
  name: cifar-fs
  args:
    data_file: filelists/cifar-fs/base.json
    transform_list: 
      - Resize
      - ToTensor
      - Normalize
    image_size: 32
    
val_dataset:
  type: json_dataset
  name: cifar-fs
  args:
    data_file: filelists/cifar-fs/val.json
    transform_list: 
      - Resize
      - ToTensor
      - Normalize
    image_size: 32

train_ep:
  batch_num: 200
  n: 5
  k: 1
  q: 15
  
val_ep:
  batch_num: 200
  n: 5
  k: 1
  q: 15

model:
  name: paper_model
  args:
    k: 9
    encoder:
      name: resnet12
      args: {}
      
optimizer:
  name: SGD
  args:
    lr: 0.001
    weight_decay: 5.e-4

max_epoch: 30